# Generated by Django 6.0 on 2026-01-24 08:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('booking', '0003_airline_flight_airline'),
    ]

    operations = [
        migrations.AddField(
            model_name='flight',
            name='price',
            field=models.DecimalField(decimal_places=2, default=100.0, max_digits=10),
        ),
    ]
